"""empty message

Revision ID: 09ac5cb142fd
Revises: e91ea12be84b
Create Date: 2021-12-29 23:42:58.986913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ac5cb142fd'
down_revision = 'e91ea12be84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'artist', 'artistcat', ['artist_catagoryfk'], ['id'])
    op.create_foreign_key(None, 'events', 'tour', ['event_tourfk'], ['id'])
    op.create_foreign_key(None, 'events', 'venue', ['event_venuefk'], ['id'])
    op.create_foreign_key(None, 'events', 'eventcat', ['event_catagoryfk'], ['id'])
    op.create_foreign_key(None, 'events', 'artist', ['event_artistfk'], ['id'])
    op.create_foreign_key(None, 'events', 'promotors', ['event_promotorfk'], ['id'])
    op.create_foreign_key(None, 'people', 'venue', ['venuefk'], ['id'])
    op.create_foreign_key(None, 'people', 'promotors', ['promotorfk'], ['id'])
    op.create_foreign_key(None, 'promotor__venue', 'venue', ['venuefk'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promotor__venue', 'promotors', ['promotorfk'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promotors', 'states', ['state'], ['id'])
    op.create_foreign_key(None, 'seating_compasity', 'venue', ['venuefk'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener3'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['headliner1'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener2'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener5'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['headliner2'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener1'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['headliner3'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener4'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'seating_compasity', type_='foreignkey')
    op.drop_constraint(None, 'promotors', type_='foreignkey')
    op.drop_constraint(None, 'promotor__venue', type_='foreignkey')
    op.drop_constraint(None, 'promotor__venue', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'artist', type_='foreignkey')
    # ### end Alembic commands ###
