"""empty message

Revision ID: 4153178ddc8f
Revises: 
Create Date: 2021-12-21 01:10:04.719440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4153178ddc8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'artist', 'artistcat', ['artist_catagoryfk'], ['id'])
    op.add_column('events', sa.Column('event_end_datetime', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'events', 'venue', ['event_venuefk'], ['id'])
    op.create_foreign_key(None, 'events', 'eventcat', ['event_catagoryfk'], ['id'])
    op.create_foreign_key(None, 'events', 'promotors', ['event_promotorfk'], ['id'])
    op.create_foreign_key(None, 'people', 'promotors', ['promotorfk'], ['id'])
    op.create_foreign_key(None, 'people', 'venue', ['venuefk'], ['id'])
    op.create_foreign_key(None, 'promotors', 'states', ['state'], ['id'])
    op.create_foreign_key(None, 'seating_compasity', 'venue', ['venuefk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seating_compasity', type_='foreignkey')
    op.drop_constraint(None, 'promotors', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'event_end_datetime')
    op.drop_constraint(None, 'artist', type_='foreignkey')
    # ### end Alembic commands ###
