"""empty message

Revision ID: 4595b9a82d45
Revises: ac58a92ad4cf
Create Date: 2021-12-16 01:28:13.693241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4595b9a82d45'
down_revision = 'ac58a92ad4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clients', 'states', ['state'], ['id'])
    op.create_foreign_key(None, 'people', 'clients', ['clientfk'], ['id'])
    op.create_foreign_key(None, 'people', 'venue', ['venuefk'], ['id'])
    op.create_foreign_key(None, 'seating_compasity', 'venue', ['venuefk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seating_compasity', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    # ### end Alembic commands ###
