"""empty message

Revision ID: 5a6076ec2175
Revises: 4595b9a82d45
Create Date: 2021-12-16 02:54:03.681063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5a6076ec2175"
down_revision = "4595b9a82d45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "promotors", "states", ["state"], ["id"])
    op.add_column("people", sa.Column("role", sa.String(length=100), nullable=True))
    op.create_foreign_key(None, "people", "promotors", ["promotorfk"], ["id"])
    op.create_foreign_key(None, "people", "venue", ["venuefk"], ["id"])
    op.create_foreign_key(None, "seating_compasity", "venue", ["venuefk"], ["id"])
    op.drop_column("venue", "dayofshow_contactfk")
    op.drop_column("venue", "preshow_contactfk")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "venue",
        sa.Column(
            "preshow_contactfk",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "venue",
        sa.Column(
            "dayofshow_contactfk",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "seating_compasity", type_="foreignkey")
    op.drop_constraint(None, "people", type_="foreignkey")
    op.drop_constraint(None, "people", type_="foreignkey")
    op.drop_column("people", "role")
    op.drop_constraint(None, "promotors", type_="foreignkey")
    # ### end Alembic commands ###
