"""empty message

Revision ID: ac58a92ad4cf
Revises: 
Create Date: 2021-12-16 01:27:06.573583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac58a92ad4cf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "promotors", "states", ["state"], ["id"])
    op.create_foreign_key(None, "people", "promotors", ["promotorfk"], ["id"])
    op.create_foreign_key(None, "people", "venue", ["venuefk"], ["id"])
    op.create_foreign_key(None, "seating_compasity", "venue", ["venuefk"], ["id"])
    op.create_foreign_key(None, "venue", "people", ["preshow_contactfk"], ["id"])
    op.create_foreign_key(None, "venue", "people", ["dayofshow_contactfk"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "venue", type_="foreignkey")
    op.drop_constraint(None, "venue", type_="foreignkey")
    op.drop_constraint(None, "seating_compasity", type_="foreignkey")
    op.drop_constraint(None, "people", type_="foreignkey")
    op.drop_constraint(None, "people", type_="foreignkey")
    op.drop_constraint(None, "promotors", type_="foreignkey")
    # ### end Alembic commands ###
