"""empty message

Revision ID: c5d00c1a8ceb
Revises: 5a6076ec2175
Create Date: 2021-12-16 02:56:51.131608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5d00c1a8ceb'
down_revision = '5a6076ec2175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clients', 'states', ['state'], ['id'])
    op.add_column('people', sa.Column('fname', sa.String(length=50), nullable=True))
    op.add_column('people', sa.Column('lname', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'people', 'clients', ['clientfk'], ['id'])
    op.create_foreign_key(None, 'people', 'venue', ['venuefk'], ['id'])
    op.drop_column('people', 'name')
    op.create_foreign_key(None, 'seating_compasity', 'venue', ['venuefk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seating_compasity', type_='foreignkey')
    op.add_column('people', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'lname')
    op.drop_column('people', 'fname')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    # ### end Alembic commands ###
