"""empty message

Revision ID: e91ea12be84b
Revises: 
Create Date: 2021-12-29 23:32:28.949241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e91ea12be84b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('artist_banner_filename', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('artist_banner_url', sa.String(length=200), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork1_filename', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork1_url', sa.String(length=200), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork1_note', sa.Text(), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork2_filename', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork2_url', sa.String(length=200), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork2_note', sa.Text(), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork3_filename', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork3_url', sa.String(length=200), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork3_note', sa.Text(), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork4_filename', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork4_url', sa.String(length=200), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork4_note', sa.Text(), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork5_filename', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork5_url', sa.String(length=200), nullable=True))
    op.add_column('artist', sa.Column('artist_artwork5_note', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'artist', 'artistcat', ['artist_catagoryfk'], ['id'])
    op.drop_column('artist', 'artist_picture_filename')
    op.add_column('events', sa.Column('event_artistfk', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('event_tourfk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'venue', ['event_venuefk'], ['id'])
    op.create_foreign_key(None, 'events', 'artist', ['event_artistfk'], ['id'])
    op.create_foreign_key(None, 'events', 'promotors', ['event_promotorfk'], ['id'])
    op.create_foreign_key(None, 'events', 'tour', ['event_tourfk'], ['id'])
    op.create_foreign_key(None, 'events', 'eventcat', ['event_catagoryfk'], ['id'])
    op.create_foreign_key(None, 'people', 'venue', ['venuefk'], ['id'])
    op.create_foreign_key(None, 'people', 'promotors', ['promotorfk'], ['id'])
    op.create_foreign_key(None, 'promotor__venue', 'promotors', ['promotorfk'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promotor__venue', 'venue', ['venuefk'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promotors', 'states', ['state'], ['id'])
    op.create_foreign_key(None, 'seating_compasity', 'venue', ['venuefk'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['headliner2'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener3'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener1'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener2'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener4'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['opener5'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['headliner3'], ['id'])
    op.create_foreign_key(None, 'tour', 'artist', ['headliner1'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'tour', type_='foreignkey')
    op.drop_constraint(None, 'seating_compasity', type_='foreignkey')
    op.drop_constraint(None, 'promotors', type_='foreignkey')
    op.drop_constraint(None, 'promotor__venue', type_='foreignkey')
    op.drop_constraint(None, 'promotor__venue', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'event_tourfk')
    op.drop_column('events', 'event_artistfk')
    op.add_column('artist', sa.Column('artist_picture_filename', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'artist_artwork5_note')
    op.drop_column('artist', 'artist_artwork5_url')
    op.drop_column('artist', 'artist_artwork5_filename')
    op.drop_column('artist', 'artist_artwork4_note')
    op.drop_column('artist', 'artist_artwork4_url')
    op.drop_column('artist', 'artist_artwork4_filename')
    op.drop_column('artist', 'artist_artwork3_note')
    op.drop_column('artist', 'artist_artwork3_url')
    op.drop_column('artist', 'artist_artwork3_filename')
    op.drop_column('artist', 'artist_artwork2_note')
    op.drop_column('artist', 'artist_artwork2_url')
    op.drop_column('artist', 'artist_artwork2_filename')
    op.drop_column('artist', 'artist_artwork1_note')
    op.drop_column('artist', 'artist_artwork1_url')
    op.drop_column('artist', 'artist_artwork1_filename')
    op.drop_column('artist', 'artist_banner_url')
    op.drop_column('artist', 'artist_banner_filename')
    # ### end Alembic commands ###
